# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=10)),
                ('text', models.TextField()),
            ],
        ),
    ]
